    </div> <!-- div[data-role="content"] -->
    
    <div data-role="footer">
        <div id="qotd"></div> <!-- div#qotd -->
    
        <h1>OCSW iPad Version <?php echo $ocsw_version; ?>.
            &copy; 2002&ndash;<?php echo date( 'Y' ); ?>.  Some rights reserved.</h1>
    
    </div> <!-- div[data-role='footer'] -->
    
</div>  <!-- div[data-role='page'] -->

<?php

$db->close();

?>

</body>
</html>